---
title: "Bed_occupancy 2010/11 to 2021/22"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(aws.s3)
library(tidyverse)
library(ggplot2)
```

This document is for scoping purposes and is not intended for use outside of the Data Analaytics team.\
Data obtained from NHS England Bed availability and occupancy https://www.england.nhs.uk/statistics/statistical-work-areas/bed-availability-and-occupancy/bed-data-overnight/

Percentage of overnight beds occupied - All England

```{r national, echo=FALSE}
## national analysis
setwd('..')
Englovernightbeds <- readRDS("England_overnightbeds.Rds")

Englovernightbeds <- Englovernightbeds %>%
  mutate(time=paste0(Year,Period)) %>%
  mutate(pctoccuptot=as.numeric(Total...14)) %>%
  mutate(pctoccupgenacute=as.numeric(`General & Acute...15`)) %>%
  mutate(pctoccupmh=as.numeric(`Mental Illness...18`)) %>%
  mutate(pctoccuptotcovid=ifelse(Year=="2020/21" | Year=="2021/22", pctoccuptot+0.01, pctoccuptot)) %>% ## add 1 percent to occupancy during pandemic
  mutate(pctoccupgenacutecovid=ifelse(Year=="2020/21"| Year=="2021/22", pctoccupgenacute+0.01, pctoccupgenacute)) %>%
  mutate(pctoccupmhcovid=ifelse(Year=="2020/21"| Year=="2021/22", pctoccupmh+0.01, pctoccupmh)) 


coeff=max(Englovernightbeds$Total...4)
ggp1 <- ggplot(Englovernightbeds) +
  geom_bar(aes(time, Total...4), color="red", stat="identity") +
  xlab("Year and quarter") +
  theme(axis.text.x=element_text(angle=90, hjust=1))
ggp2 <- ggp1 +
  geom_line(aes(time, pctoccuptotcovid*coeff, group=1), color="blue", lwd=2 ) 
ggp3 <- ggp2 +
  scale_y_continuous(name="No. of beds", sec.axis=sec_axis(~./coeff, name="proportion occupied")) +
  ggtitle("Total overnight beds") 
ggp3


coeff=max(Englovernightbeds$`General & Acute...5`)
ggp1 <- ggplot(Englovernightbeds) +
  geom_bar(aes(time, `General & Acute...5`), color="red", stat="identity") +
  xlab("Year and quarter") +
  theme(axis.text.x=element_text(angle=90, hjust=1))
ggp2 <- ggp1 +
  geom_line(aes(time, pctoccupgenacutecovid*coeff, group=1), color="blue", lwd=2 ) 
ggp3 <- ggp2 +
  scale_y_continuous(name="No. of beds", sec.axis=sec_axis(~./coeff, name="proportion occupied")) +
  ggtitle("General & acute overnight beds") 
ggp3

coeff=max(Englovernightbeds$`Mental Illness...8`)
ggp1 <- ggplot(Englovernightbeds) +
  geom_bar(aes(time, `Mental Illness...8`), color="red", stat="identity") +
  xlab("Year and quarter") +
  theme(axis.text.x=element_text(angle=90, hjust=1))
ggp2 <- ggp1 +
  geom_line(aes(time, pctoccupmhcovid*coeff, group=1), color="blue", lwd=2 ) 
ggp3 <- ggp2 +
  scale_y_continuous(name="No. of beds", sec.axis=sec_axis(~./coeff, name="proportion occupied")) +
  ggtitle("Mental Illness overnight beds") 
ggp3

```

Percentage of overnight beds occupied - by region

```{r regions, echo=FALSE}
## regional analysis
setwd('..')
bedoccup <- readRDS("bedoccup.rds")

bedoccup <- bedoccup %>%
  mutate(timeyr=substr(Year,1,4)) %>%
  mutate(timeyr=as.numeric(timeyr)) %>%
  mutate(timeqtr=ifelse(`Period End`=="June", 1,
                        ifelse(`Period End`=="December",3,
                               ifelse(`Period End`=="March",4,2)))) %>%
  mutate(time=paste0(timeyr,timeqtr)) %>%
  mutate(timenum=as.numeric(time)) %>%
  mutate(pctoccuptot=as.numeric(Total...18))

bedoccup2019_2021 <- filter(bedoccup, timenum>20184)
bedoccup2019_2021$`Region Code` <- factor(bedoccup2019_2021$`Region Code`, labels=c("London", "Southwest", "Southeast", "Midlands", "East", "Northwest", "Northeast"))
mytable <- table(bedoccup2019_2021$time)
mytable

aggregate(bedoccup2019_2021$pctoccuptot, list(bedoccup2019_2021$`Region Code`), FUN=mean, na.rm=TRUE)

summocc <- bedoccup2019_2021 %>%
  drop_na(pctoccuptot) %>%
  group_by(`Region Code`, time) %>%
  summarise(meanoccup=mean(pctoccuptot), n=n())

ggplot(data=summocc, aes(x=time, y=meanoccup, group=`Region Code`)) +
  geom_line(aes(linetype=`Region Code`, colour=`Region Code`)) +
  ylim(0.5,1.0) +
  ggtitle("2019-2021") +
  ylab("% occupied") +
  xlab("Year and quarter") 


bedoccup2015_2017 <- filter(bedoccup, timenum<20181 & timenum>20144)
bedoccup2015_2017$`Region Code` <- factor(bedoccup2015_2017$`Region Code`, labels=c("North", "Mids & East", "London", "South"))

aggregate(bedoccup2015_2017$pctoccuptot, list(bedoccup2015_2017$`Region Code`), FUN=mean, na.rm=TRUE)

summocc <- bedoccup2015_2017 %>%
  drop_na(pctoccuptot) %>%
  group_by(`Region Code`, time) %>%
  summarise(meanoccup=mean(pctoccuptot), n=n())
ggplot(data=summocc, aes(x=time, y=meanoccup, group=`Region Code`)) +
  geom_line(aes(linetype=`Region Code`, colour=`Region Code`)) +
  ylim(0.5,1.0) +
  ggtitle("2015-2017") +
  ylab("% occupied") +
  xlab("Year and quarter")



```


